#
# ⚠️警告⚠️：如果发现无法删除Workflows运行历史，需要将仓库Workflow permissions设置为：Read and write permissions
# 未知： Settings -> Actions -> General -> Workflow permissions
#


name: Delete All Workflows - yanovian


on:
  # schedule:
  #   - cron: '0 0 * * *'  # Specify your own schedule
  workflow_dispatch:     # Allows manual runs from the Actions tab

permissions:
  actions: write         # Required to delete workflow runs
  contents: read

jobs:
  prune-old-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Delete workflow runs
        uses: yanovian/prune-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: 0